language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4.0"
  - "5.0"
  - "6"
sudo: false
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
